### ISSUE TITLE
SEPIO: AlleleConservation refactor request

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#146]
@cbizon @bpow @tnavatar 

Please review [AlleleConservation issue from MB](https://docs.google.com/document/d/1yMnJnnGMard0Cqu86Cx0gv7gX0b0RaAjgU7Zl8ucxnQ/edit#bookmark=kix.kqr0yypp0j0) 
(NOTE: there are notes at the very bottom of the doc related to this discussion too)

**Comment by cbizon** [comment]
We have a quantitative score and a qualitative score.  One option is to make the qualitative score "the" score (the output) and the quantitative score is a certainty of that quantitative score.   But this is incorrect.  They are both measures of the same thing: whether the allele is conserved. They are just expressed in different ways.     That is: the quantitative score is not a measurement of certainty, it is a measurement of conservation.

I think that the most consistent way to do this would be to have a QualitativeAlleleConservation and a QuantitativeAlleleConservation.   Because they are Statements, the Qualitative one could have an evidence line that points to the Quantitative one.  One nice thing is that if you only wanted one or the other, you could just include that one, don't support it and move on.

That's very clean, but: 1) It means we need to split the class in two 2) the model becomes more complicated to parse (increase from 1 object to 3).  It feels like we're adding nodes to describe something as simple as a unit conversion. ( know that this is 1 meter long because it is 100 cm long)  That's a clean and correct way to do this, but it's overkill, I think.

I guess, in the end, I'd prefer to have a quantitative score, and a qualitative score in the same object. The difficulty seems to be a Finding vs. Assertion problem, but TBH, I don't recall why that was a big deal.

**Comment by cbizon** [comment]
I'm putting the above into Matt's doc so that he sees it too.

**Comment by bpow** [comment]
@larrybabb : you may be in the middle of this, but in case you didn't notice, Conserv{259, 260, 263, 264, 267, 268, 071, 072} have references in the sheets (and should be split into qnt/cat statements).

**Comment by larrybabb** [comment]
i am in the middle. so sorry. i'll let you know when I'm done.

**Comment by larrybabb** [comment]
completed
