### ISSUE TITLE
Example Diagram Page Updates

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-interpretation#147]
Team, (@bpow @larrybabb @cbizon @nafisakhandaker)  
     Let me know what you think of the update for the Examples Page (https://github.com/clingen-data-model/clingen-interpretation/commit/be38239b073b2621787b87f48010f342e6d43c6b)  It was just committed to the master.  If you are pleased, feel free to close the ticket, else add your feedback and I will try to address.

**Comment by larrybabb** [comment]
Awesome. You rock.

If you could make the JSON window's height expand and contract with the bottom edge of the browser window, that would be great.  Or even if you wanted to just spew out the json into the page and let the browser's scrollbar be the mechanism for scrolling (instead of the nested frame). Sort of like the Tabular View.  

Extra for experts (just for fun of course).  A link at the top of the  json tab that lets you copy the entire json message to the clipboard or download to a file., would be handy (at least I think so).  These could get long and copying might be a drag (excuse the pun).

**Comment by sgoehringer** [comment]
Updates to the JSON doesn't scroll https://github.com/clingen-data-model/clingen-interpretation/commit/d3376ba6fbfa14db0c235920b22b09962ff52aa1  

I need to look into the copy further.

**Comment by bpow** [comment]
Well, power users can click in the json window, then press the `select-all` key combo and `copy` key combo of their respective operating systems 😃 . But I would not be averse to a "copy" button if ace editor doesn't make that too difficult.

Otherwise, looks great!
