### ISSUE TITLE
Better formatting on content sidebar

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#181]
I've added a bunch of discussion pages, but now the sidebar is kind of hard to read:

There are 5 discussion topics.  Each has a multiword title, and the breaks that get put in make it hard to read (see image)

![image](https://user-images.githubusercontent.com/10744350/34569537-17126078-f137-11e7-846c-8a5679e7a001.png)

I'm not sure whether we want to have another tag with a shorter name for the sidebar, or just have short titles, or some kind of bullet, or spacing, or what. I defer to people with design sense/skill.

**Comment by larrybabb** [comment]
Yes, I've run into this too. I think we definitely want to manage the menu sidebar titles to allow for shorter (thumbnail) versions of the actual titles on the pages.

**Comment by bpow** [comment]
Not sure if there is a better issue to discuss this, but we keep moving around the organization of the menus and I don't know that anyone is ever happy with it...

Right now, we have:

* Interpretation Overview
* User Guide
  * Discussion
    * many sub-pages...
  * Examples
  * Projects
  * Release Notes
  * SEPIO
* Technical Reference
  * Entity Definitions
    * many sub-pages...
  * JSON Schema

I'm not really fond of having the extra level to get to the entity definitions that happens by having the "Technical Reference" section (which also incorporates the JSON schema right now). I think JSON schema itself could go to a top-level (or maybe in an "Information Artifacts" section or something with a better name that could also include the json-ld context, link to relevant owl files).

We've stuck with these ideas of "User Guide" and "Technical Reference", and had many discussions about for what audience they are each intended...

Howzabout we just title them more by what they do?

User Guide => Understanding the model
Technical Reference => Entity Definitions

Rather than discuss this again on a call, I think it would be helpful to have some people put some thoughts in writing (like in #185 ) to focus the discussion.

**Comment by larrybabb** [comment]
done during recent re-org of site.  more to come when we fully consolidate modeling sites under one project.
