### ISSUE TITLE
@context and curies

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#182]
We use curies all over the place.  Don't we need to define the prefix somewhere and isn't that somewhere the context?  I don't think that they're in there.

Also, there's at least one stray "\n" floating around in there:

"Statement": {
      "@id": "SEPIO:0000174\n"
    },

**Comment by bpow** [comment]
The spare "\n" was easy to fix-- it was being faithfully represented since it is in the sheets document. I think the prefixes may have at one point been part of the IdentifierSystem objects, but there is also a separate _prefixes sheet. I don't recall what the difference is supposed to be (or if there is supposed to be a difference) but will look into this.

**Comment by bpow** [comment]
5bfad98 should close this, so long as all relevant cURI prefixes needing to be included in the context are associated with an IdentifierSystem
