### ISSUE TITLE
Fix description for CaseCtrl030

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#189]
Currently says "Treating ExAC data as controls for", which is not a complete sentence or phrase. I'm not sure what this is supposed to say.

**Comment by larrybabb** [comment]
So I went back to the original version when this was structured by @cbizon in the text document that steven harrison wrote up.

Here's the original text for this PS4 #1 example from SHarrison

> Assessed variant: SLC26A4 NM_000441.1:c.1003T>C (p.Phe335Leu)
>  
> Across all published data (and LMM data) the c.1003T>C variant has been identified in 32 chromosomes with hearing loss of 4076 total hearing loss chromosomes assayed (32+ ; 4044-). In ExAC (http://exac.broadinstitute.org/variant/7-107329499-T-C) this variant is found in 105 / 121336 total chromosomes.
>  
> Case control comparison shows statistically significant difference between affects and unaffected (OR 9.1361 99%CI: 6.1425 - 13.5889)


I think @cbizon drafted the "explanation" for the CaseCtrl030 entry and left the sentence open ended because it is for "the group allele frequency" attribute contained within it.  Here's the original structured form from @cbizon.  Maybe the simple solution is to put "... controls for **'the groups found in all published data (and LMM data) with hearing loss'.**"

```
CaseControl:
ID: CC1
Allele: CA22
Condition: C7
odssRatio:9.1361
confidenceInterval:99%CI: 6.1425 - 13.5889
caseGroup: GAF1
conrolGroup:: PAF1
Explanation: Treating ExAC data as controls for 

GroupAlleleFrequency
ID: GAF1
Ascertainment: Across all published data (and LMM data) with hearing loss.
Allele: AI22
alleleCount: 32
alleleNumber:4076

PopulationAlleleFrequency:
ID: PAF1
Ascertainment: ExAC
Allele: AI22
alleleCount:105
alleleNumber: 121336
```

I'm not super confident when it comes to modifying the content of the sample data. So, I will need @cbizon or @bpow  to validate my proposal here.

**Comment by cbizon** [comment]
I think the simplest thing is to strike the word "for"

**Comment by bpow** [comment]
I agree with @cbizon and will go ahead and do so. Anyone can re-open if they would like to discuss further.
