### ISSUE TITLE
Strength adjusted evidence codes

### ISSUE THREAD

**Issue by ronakypatel** [clingen-data-model/clingen-interpretation#191]
I have a trouble figuring out, how to incorporate strength adjusted evidence codes in SEPIO-ACMG.

Say for example I want to document **PVS1-Strong** (Strength downgrade) using interpretation model.

Is this correct?

evidenceLine.evidenceItem.criterion.label => PVS1
evidenceLine.evidenceItem.criterion.defaultStrength => Pathogenic Very Strong
evidenceLine.evidenceStrength => Pathogenic Strong

Please correct me if I am wrong.

**Comment by larrybabb** [comment]
Yes, that is correct.  
In reality you don't necessarily have to share the "defaultStrength" at all. I say this because the "defaultStrength" is inherent to the definition of the criterion codes. In other words, it never changes and is part of its fundamental definition.  We modeled it because there is no public stable model of these criterion codes and their defaultStrengths, so we simply pass all the criterion information with each *.criterion.* structure.  Ideally, this will be coded and published in a stable available resource someday and tools could look it up separately if needed.
