### ISSUE TITLE
RegionTypesAndAlleles change request

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#57]
@cbizon @bpow 
On the RegionTypesAndAlleles data type we have two attributes
1) isTypes[], CodeableConcept, 0..* - the array of region types that this specified region "is"
2) isNotTypes[], CodeableConcept, 0..* - the array of region types that this specified region "is not"

I would prefer to change this. My argument is that these two properties are mutually exclusive and I don't think it would make sense to use them concurrently for a single instance of the class.  
Assuming that is a fair and reasonable argument, I think it would be preferred to change it to the following for a bit more clarity and to be more consistent with other similar patterns applied in some of the other classes that have a true/false flag to denote when the qualifying property applies or does not apply.

Here is the recommended change...

1) types[], CodeableConcept, 0..*, the array of types which are explicitly being expressed to qualify or not qualify the region based on the cross-referenced attribute "isType"
2) isType, boolean, 1..1, default=TRUE - the boolean flag indicating whether the "types[]" list of coded region types represent the types of the region or do not represent the types for that region.

Please let me know your thoughts asap.

**Comment by cbizon** [comment]
I like your recommended change.

**Comment by larrybabb** [comment]
awesome to hear, but I recognized afterwards that we have 2 other properties which are somewhat similar (includeAlleles[] and excludeAlleles[]). 

Should I apply the same pattern and convert that to the following (as well)?
alleles[] : CanonicalAllele array 
included : boolean (defaults to TRUE)

I'm just not 100% confident that we planned to be able to have both included and excluded alleles in the same structure.  

If you could weigh in on this I think I can close the book on this data type for (a while) at least.

Thanks.

**Comment by cbizon** [comment]
Yeah, I think alleles[] and included is fine in this case too.

**Comment by bpow** [comment]
This whole type is still confusing to me, as I've related before.

What is the use case exactly for `isNotTypes`? If we can't come up with one, then we should just have a `types` array (or whatever we end up calling it) and leave out the isType boolean.

I remain convinced that the statement that an allele is in or out of a region is an assertion/prediction of sorts, and I don't like conflating the two since there's no real way that a given "RegionTypesAndAlleles" object could truly enumerate all of the respective alleles. Especially if we allow for notating excluded alleles.

I can't say I understand what you are doing with the type well enough to comment more than this without further discussion/explanation.

**Comment by cbizon** [comment]
Obsolete by interactions with Matt/Sepio
