### ISSUE TITLE
Apparently PublicationStatus (E37) is gone?

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#58]
Working on getting @larrybabb sheet updates in place...

E37 no longer exists as a type, I'll go ahead and delete the placeholder it has in the docs.

@larrybabb -- feel free to close this issue if this is correct (if you really meant to remove this type).

**Comment by bpow** [comment]
Likewise E27 (ConditionInheritance) and E15, I'm pretty sure you did mean to remove these as you are merging them into other entities...

**Comment by larrybabb** [comment]
To be clear, I did get rid of these types in the new version of the spreadsheet.  So I will close this.
But do confirm that we are now working with the DMWG-ACMG Rule Examples Data (with EvidenceLines) data sheet at this point.  Because I am still making changes there and would hate to be working in parallel.

**Comment by bpow** [comment]
Yes, the middleman docs are pulling from the new sheets document
