### ISSUE TITLE
inheritance?

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#61]
Where is inheritance in the JSON?  For our examples, there is no structured inheritance in the interpretation or mendelian condition, except as part of the condition name.  For instance, in VarInterp274, AR only appears here:

` 
"condition": [
    {
      "cg:id": "MendCond004",
      "cg:type": "MendelianCondition",
      "explanation": "Primary ciliary dyskenisia, Autosomal Recessive"
    }
`

Shouldn't it be an explicit property of either VariantInterpretation or MendelianCondition?

**Comment by bpow** [comment]
Essentially the same problem as #62 : the data is in _MendelianConditionAttribute...

**Comment by cbizon** [comment]
Related, yes, but I want to be sure to explicitly address/document that the inheritance is a member of the condition, not of the interpretation.

Is there ever a reason that one would say "This variant is benign for all dominant conditions"?  I can't think of one.

**Comment by larrybabb** [comment]
In the spreadsheet the MendelianConditionAttributes are broken out to have separate attributes (one for disaease-orpha and one for inheritance-hpo.

I think @bpow will be modifying the generation of the MendelianCondition to support the CodeableConcept construct to look something like ...

BTW - I'm not sure we should use the "explanation" value in the MendelianCondition sheet.  I did provide a "name" attribute for situations whereby a user wanted to provide a preferred text name representation for the Mendelian Condtion in the event that there was no coded disease/pheno or that it differed and was not desireable.  The "explanation" field in the spreadsheet currently derives its value by either looking for this "name" attribute otherwise it comma separates any disease or phenotypes with the MOI attributes.  In other words, its a bit wonky.  

```
"condition" :  {
    "explanation" : "Primary cliiary dyskenisia, Autosomal Recessive",  -- don't use this? (use "name" if provided!
    "disease" : {
        "coding" : {
            "system" : "Orphanet",     -- or the system id for orphanet
            "code" : "244",
            "display" : "Primary ciliary dyskenisia"
        }
    },
    "modeOfInheritance" : {
        "coding" : {
            "system" : "HPO",     -- or the system id for HPO
            "code" : "0000007",
            "display" : "Autosomal Recessive"
        }
    }
}

```
