### ISSUE TITLE
Mendelian Condition JSON

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#62]
The JSON for Mendelian Condition has a property called "explanation" that includes the condition name.  Shouldn't this be something more like "condition"?

**Comment by bpow** [comment]
The "explanation" comes from a computed field in the sheets document, and to some extent represents a "toString" for display purposes. Each MendelianCondition should have at least one "disease" attribute (A158, probably better named "condition") that you are looking for.

It's not in the JSON yet because _MendelianConditionAttribute is a separate sheet from _DataAttribute, so I will need to special-case it in the reformatting code.

Or I think we could just move the rows from _MendelianConditionAttribute to _DataAttribute. @larrybabb , do you see any reason to keep these sheets separate? We could still keep MendelianCondition separate from Data (otherwise we would have to re-number all of the MendCond records, which would be a pain).

**Comment by larrybabb** [comment]
I think I’m fine with merging MendelianCondition inot Data. But, I would merge both (I’ll deal with the renumbering issue). I think we should hold on doing this until we’ve had a discussion with Matt Brush on this concept and verify that we are content with this concept’s structure and application.

 

We can put it on the docket for today?
