### ISSUE TITLE
Fix representation of CodeableConcepts/ValueSets in the json message format

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#68]
Should be something similar to FHIR:

```JSON
{
  "@id": "http://purl.obolibrary.org/obo/HP_0000007",
  "coding": {
    "system": "http://human-phenotype-ontology.github.io/",
    "code": "HP:0000007"
  },
  "text": "Autosomal Recessive"
}
```

If anyone wants to comment on this or come up with more structured examples, I'd be happy to have a look.

**Comment by bpow** [comment]
Note that in FHIR, "text" is 0..1, "coding" is 0..*, and system and code are both 0..1. Do we want to be more strict than this?

What should we use for "system" for codings?

**Comment by larrybabb** [comment]
I do not think we need to be more strict. The idea is that the producer can convey a "text" only representation in the event that they are technically or logically unable to find a representative code from a legit authority.
On the other hand, some other producer can send only a code or set of codes and no text.  

In FHIR I believe the coding has another "type" attribute (which we do not include) which can be used to say whether or not the user selected it, or it its the primary or a secondary code.  I didn't go as far as pulling that in.

But I do think flexibility is the best here. We can recommend in a spec that a code is always used and that the ClinGen "preferred" disease names are used when appriopriate and such.

I do think we also want to add the third field under coding for the "display" which would provide a "human readable" form that is associated with the coding authorities code in case a "text" value is not specified.

**Comment by bpow** [comment]
I guess by being "more strict", I was also potentially including the possible restrictions of requiring a `coding` (i.e., making it 1..*; which might kinda' be against the point of the flexibility of having a CodeableConcept to begin with) or of requiring at most 1 `coding` (so it would be 0..1). Just trying to think through the options...

Do you expect CodeableConcept.text will always be the same as Coding.display when the latter exists?

**Comment by bpow** [comment]
Looking more closely at how you have organized things in the sheet, @larrybabb , it seems that the `ConceptDefinition` sheet describes `Coding`s, and `ValueSetConcept` describes `CodeableConcept`s (while also listing which `ValueSet` a `CodeableConcept` is part of).

Would it make sense to rename those sheets to their appropriate types and then to have a joining table to describe the relationship between `ValueSet`s and `CodeableConcept`s? It seems like this is currently one-to-many, but I could imagine that it might be many-to-many (a concept could more generally be part of multiple `ValueSet`s.

At some point, we will have to think about how we represent a `ValueSet` (full FHIR-like specification with 'compose' and 'include' and things like that, or a more restricted definition?).

**Comment by larrybabb** [comment]
I don't think that's quite what was intended (while I understand the confusion).  I do agree that Codings are equivalent to ConceptDefinitions.  However, ValueSets contain concepts (or codings) that may come from a heterogeneous set of Coding authorities, but only when done with care.  
While this may seem overly complex for our purposes, it is quite watered down from the much more complex requirements and purpose defined by HL7.  If you were to read the ValueSet page in the FHIR spec you might see the purpose more clearly. I think of it more formally for us as a means of publishing the specific "bindings" and rules for what terms and constraints we may have around controlled vocabulary for specific attributes throughout the message structure.

I think that anywhere we bind a ValueSet, the target attribute can contain one or more "Coding" from the associated ValueSet's list of codings or alternatively some freeform text or potentially a different Coding (if the Value Set binding is defined to allow this).

**Comment by bpow** [comment]
Yes, I think I understand the structure and rationale of CodeableConcepts, ValueSets, etc. in FHIR, I may not be asking my question well, which is more about how we are currently using them in our examples (which is more along the lines of using the sheets to group things) and what we might need to do going forward to really make our use more meaningful (e.g., more formally specifying the expected/allowable domain of ValueSets). This might bear discussion on a conference call.

**Comment by bpow** [comment]
I'm going to have another go at discussing this, and maybe we can bring this up on a call.

I think that what we need (at least for documentation in the short term) is to represent the `CodeableConcept` and `Coding` types following the way they are used in FHIR (probably with a subset of attributes that are useful to us...). I've started to do this in the sheets document.

To populate the examples with these, we would need represent the codeable concepts in the data. Currently these are referred to (sheets like _InformationAttribute) just by their string value (really the `Coding.code`. They don't have an `id` _per se_ (at least not one defined by us like "CC014" or anything).

Do we want to try to avoid having an `id` for CodeableConcepts (FHIR doesn't require one, but everything in FHIR inherits from a base object with an `id` attribute, so it wouldn't be awful to include it)?

The sheet currently called `ConceptDefinition` actually has the info necessary to define `Coding`s. I don't think we have any examples yet where we would use more than one `Coding` for a `CodeableConcept`. Is this a use case we want to track? Even if so, is it something we just want to allow but not have examples for (in which case our example generation does not have to support it)?

**Comment by larrybabb** [comment]
@bpow The MendelianCondition is somewhat related in that it represents a "Coding" (the disease code) and a "name" (or text) field.  It's a bit more contrived than that because we added the qualifier for inheritance. But it is important to note that many users submit to ClinVar with simply a name for the disease and no codes. They will probably do this for inheritance and a number of other Coding-related fields.

I realize we don't have an example, but I can think thru this more and figure out how to refactor (minor refactor) the related codes such that they point to a "CodeableConcept" entity page which allows you to generate things more reaonsably.

Does that sound okay?

**Comment by cbizon** [comment]
@bpow and I just had a long conversation about this, and I have to admit that I'm slightly uneasy about the use of CodeableConcept in our messages.  I've been a little hesitant to get into it, because I have had a hard time putting into words what was bothering me about it.  I'm going to try anyway.   Some of this is related to what @bpow said, but don't blame him for any misstatements that I make.

It basically feels that codable concept is non-idiomatic for a JSON-LD message.  In JSON-LD, you have an entity and the ID defines the identity of it.  You don't have to give a system for it, because the IRI points right at the thing itself.   If you want to, you can define a prefix in the context that can be interpreted as a system.  So if the IRI is `http://purl.obolibrary.org/obo/HP_0000007`  you can define that `HP` is the same as `http://purl.obolibrary.org/obo/` and then your IRI can be expressed as `HP:HP_00000007` and the first part is the system and the second part is the term.  If you want to pass a name as well, you can pass a name tag with the IRI but you don't have to, and you don't need anything else either.

That approach is simpler and more idiomatic, but I think that there are certain things that you can't do with it.   One thing is that you can't really say that there is more than one coding for a concept.  So the main question I guess I have is: "do we have real uses cases where the extra complexity and non-idiomatic nature of codable concept is required?"   I would imagine that the answer to this question would be yes for some places where we might use codable concept, and no in other cases.  I'm unclear at the moment which places we want to use them, so it's tough to go further.

**Comment by larrybabb** [comment]
Codeableconcept as directly used in FHIR is no longer relavant here. We will have documentation on our ValueSet page that refers to how FHIR codings and codeableconcepts relate to ValueSet concepts in our model.
