### ISSUE TITLE
inheritance modifiers

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#69]
The VCI has a mode of inheritance, but it also has an inheritance modifier: 

![image](https://cloud.githubusercontent.com/assets/10744350/25193696/f4efafee-2505-11e7-9b70-99fda11a752a.png)

```
"modeInheritance": "Autosomal dominant inheritance (HP:0000006)"
 "modeInheritanceAdjective": "with maternal imprinting (HP:0012275)"
```

Do we want to capture this stuff?  Do we want to buff our inheritance model?  I think we might...

**Comment by tnavatar** [comment]
+1 for capturing this stuff.

**Comment by larrybabb** [comment]
I've been looking at Matt Brush's models related to "is qualified by" relationships to the assertions version our "MendelianCondition" concept.  Doesn't this qualify the MOI? If we add this to the MendelianCondition, then we would need a substructure (I think).  Do we really need to sub-qualify the MOI?  Isn't this what HPO is for?  Or should this be a CodeableConcept....

```
...
"modeOfInheritance": { 
    "text" : "AD with maternal imprinting",
    "coding" : [{"system" : "hpo", "code":"0000006", "display":"Autosomal dominant inheritance"}]
}
```

**Comment by cbizon** [comment]
Yes, I agree with @larrybabb .   I didn't realize that HP:0012275 was actually "Autosomal dominant inheritance with maternal imprinting".  I thought it was just the maternal imprinting part.  I will ask Karen whether they have a reason for doing it this way, and for a full list for their "modeInheritanceAdjective" drop down.

**Comment by larrybabb** [comment]
This may raise an interesting issue around the use of hierarchies or ontologies with ValueSets.  
And it does potentially create a challenge on the downstream side when translating this info into the ClinVar constrained values.  At that point, we may need to find the higher level term but somehow keep the actual term so that we do not change the original authors meaning.  

Or we say "not our problem" and have VCI work it out with ClinVar.

**Comment by cbizon** [comment]
That's a good point.   I guess I think that we should target the more expressive set of values for our model, and then figure out how to help get the VCI data into ClinVar, which might involve some discussions with each of those groups, which we can try to mediate or not.

**Comment by rrfreimuth** [comment]
I agree.  This is really a terminology mapping problem, which we all know never really go away.  I think we should capture the most detailed information we can get - understanding that we may still face a decision about whether to use a precoordinated term or a set of post-coordinated terms - because once the semantics are abstracted into a higher level term the information is lost.

This sounds like a discussion that needs to occur between VCI and ClinVar, and while I agree that we are in a position to mediate I suspect it will ultimately be up to those groups to craft the solution (we have limited ability to do that).
