### ISSUE TITLE
Should VariantInterpretation and CriterionAssessment have a shared superclass

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#81]
Both `VariantInterpretation` and `CriterionAssessment` represent assertions... both could presumably map to SEPIO:0000001 (SEPIO:assertion). Both have the attributes expected from assertions ('hasEvidence' and 'contribution').

Should we extract out the superclass/interface that has these properties?

Should they map directly to `SEPIO:assertion` in the JSON-LD, or should they map to cg:VariantInterpretation and cg:CriterionAssessment, with the understanding (somehow) that they could also be interpreted as `SEPIO:assertion`s?

**Comment by cbizon** [comment]
I had imagined that we would just give sepio assertion as the type of these elements, but I would be open to other ways of doing this.   It's also possible to give things more than one type, so we could do:
```
"@type": [ "SEPIO:assertion", "CG:VariantInterpretation"]
```

**Comment by bpow** [comment]
Good point about making `@type` a list, maybe we should go ahead and have an internal IRI even for those types that have an identified external IRI.

**Comment by tnavatar** [comment]
In this case it might be a bit cleaner to have a two different types and use just one type per instance ({type: CG:VariantInterpretation} and not {type: [ "SEPIO:assertion", "CG:VariantInterpretation”]}) The subclass relationship of both to SEPIO:assertion could be specified via an ontology we maintain. While it’s definitely appropriate to have more than one type per object, in this case there would never be a CG:VariantInterpretation that isn’t also a SEPIO:assertion, so that’s probably best specified in an outside ontology.

**Comment by bpow** [comment]
Hmm... I'm not sure I follow.

I agree that it is redundant to state that a CG:VariantInterpretation is also a SEPIO:Assertion, since that would presumably always be true. However, I think this may be an acceptable level of redundancy since it would allow downstream use of the data as a SEPIO:Assertion even if client code had no idea of our ontology or what a CG:VariantInterpretation is.

**Comment by tnavatar** [comment]
That’s a reasonable concern, though I suspect that people who care about SEPIO:Assertions would be hip to Linked Data. I don’t think there’s a big problem here whatever we decide.

**Comment by larrybabb** [comment]
This ended up mapping to SEPIO:statement iri.
