### ISSUE TITLE
fix insilico pred attribute change to canonical allele

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#84]

**Comment by bpow** [comment]
This issue is to address the use case of converting from the VCI to our data model. @cbizon noted that the VCI draws upon some external data (e.g. predictions precalculated in dbNSFP by way of mygene.info) for which contextual alleles are not defined, but there may be a canonical allele and a specific transcript.

His proposal (provisionally accepted on teleconference call) was to change the allele attribute in InSilicoPrediction to point to a canonical allele instead (as required field) and to allow an optional transcript field. This allows a prediction just on a canonical allele (for cases when no transcript info is provided) or would allow a downstream user to generate a contextual allele through the combination of CanonicalAllele and transcript.

To fix the sheets, every attribute A096 in _InformationAttribute will need to be changed to point to the appropriate CanonicalAllele instead of ContextualAllele, and the transcript used in the ContextualAllele will need to be brought up to the InSilicoPrediction.

**Comment by larrybabb** [comment]
The sheet has been updated so that the InSIlicoPrediction examples now contain the corresponding transcript and canonical allele based on the original contextual allele that was previously associated.
