### ISSUE TITLE
Code prefixes

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#87]
I'm working on the value sets.   For something like MolecularConsequence we are relying on external codes so we say something like

display=missense_variant
code = SO:0000181 (or whatever it is)

For others, like VS004 (region_annotation_type), we have the list of display names (repeat, eg) but what is the form of the code? Is it

CG-reg-anno-type:repeat
or 
CG:repeat
or
CG-interpretation:repeat

We now have the first kind, where this namespace is at the VS level.  I think that's probably the best way to go, but in something like SO, or HPO, they just have one large namespace and put everything into it.  What do we think?

**Comment by bpow** [comment]
I think @larrybabb had discussed setting it up that way ("namespaced" within CG by valueset) to try to avoid having to have all of the ValueSet members have unique names/represent unique concepts.

**Comment by larrybabb** [comment]
There's a couple of points that should be clarified here. (I think)

First, in our example sheet we need a single value that can act as a key (FK->PK) so that we can put a value in our _InformationAttribute column C (aka Value column) and have it foreign key to the actual Coding in the other sheet.  For this I used <code system namespace abbreviation>:<code> which enable me to contrive a unique value for use as a primary key in the Coding sheet.

So, the SO:0002054 really should never show up anywhere in our messages, similar to all the other made up ids.  When we render the Coding or the analogous IRI for a coding we should use   (my best guess actually )
```
{
  "id" : "http://sequenceontology.org/0002054",
  "type" : "Coding"
  "code": "0002054",
  "display": "loss of function variant",
  "system": "http://sequenceontology.org"
}
```
does that help?

**Comment by bpow** [comment]
Actually, @larrybabb, I was seeing things a bit differently. I had thought that the namespaced prefixes would be part of our messages, but the json-ld context would map them to full IRIs... so the message with inline context might look something like:

```json
{
  "@context": {
    "id": "@id",
    "type": "@type",
    "cg": "http://clinicalgenome.org/datamodel/",
    "CG-reg-anno-type": "cg:region-annotation-type/",
    "CG-codeable-concept": "cg:codeable-concept/",
    "code": "CG-codeable-concept:code",
    "display": "CG-codeable-concept:display",
    "system": { 
      "@id": "CG-codeable-concept:system",
      "@type": "@id" 
    }
  },
  "id" : "CG-reg-anno-type:repeat",
  "type" : "Coding",
  "code": "repeat",
  "display": "Repeat",
  "system": "http://clinicalgenome.org/datamodel/prediction-type/"
}
```

The "id" can still be represented as a full IRI by taking the context into account.

**Comment by larrybabb** [comment]
perfect.

**Comment by cbizon** [comment]
This is all now handled in our context
