### ISSUE TITLE
Genetic anticipation

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#88]
Related to #69 .  

One of the modifiers for inheritance that the VCI uses is "Genetic Anticipation".  It has an HPO code, and it descends directly from mode of inheritance.   Genetic Anticipation is a type of inheritance where the phenotype gets stronger with each generation, usually because the allele is some kind of repeat and the number of repeats of the motif is growing each time.

Genetic anticipation is usually seen in a dominant setting, because for recessive diseases you don't tend to have subsequent generations with the disease, but there is at least one recessive disease that is capable of displaying genetic anticipation.

For most diseases with this, you'll want to say that the inheritance is both dominant and genetic anticipation.  How do we want to handle this?

1. We could make mode of inheritance a list, and be able to include both
2. We could define terms: "Dominant with genetic anticipation" etc.  But there will be a lot of these.
3. We could do what the VCI does and have a regular "mode" and then a "modifier" where this would go.
4. We could assert that genetic anticipation is out of scope for ACMG style guidelines.

My inclination is (1) but I don't really like any of these so far.

**Comment by larrybabb** [comment]
The level of the MOI is very important to conveying information that can be used without the inclusion of an ontological model integration service.
I think that all of our "code lists" or value sets that bind to attributes should be root level terms with the same degree of specificity.  
I realize the disease and phenotype ontology is a special beast which will require ontological associations (parents/children).  
But I think that this may be too complex of a technical requirement to start using any element within any level of a branch of an ontology in a single attribute.

For example in your question above "genetic anticipation".  Why wouldn't it be both a child of Recessive and Dominant, if it can be either.  If not why isn't it specifically labeled as dominant with genetic anticipation and recessive with genetic anticipation, etc...  Is there a reason why the HPO experts don't see genetic anticipation as a child of Recessive?

There are points in the lineage of ontologies where terms begin to change into a different "class" of a thing that would then meet the constraints of the attirbutes and concepts we are attempting to control and share in our messaging model.

I could be okay with defining the scope of MOI to include one or more levels of ontological concepts from the same neighborhood under the single node that best maps to mode of inheritance.  But, we must weigh things to be technically pragmatic versus ideally computable.

**Comment by cbizon** [comment]
My impression is that recessive genetic anticipation is very rare and that is why HPO did not include a recessive version, which they easily could have done.

**Comment by bpow** [comment]
A few comments:

1. There is a list of terms for ModeOfInteritance used in ClinVar
 (ftp://ftp.ncbi.nlm.nih.gov/pub/GTR/standard_terms/Mode_of_inheritance.txt) that is based on HPO. 

2. Although anticipation in autosomal recessive conditions may be very rare, it does exist (at least to the extent of triplet repeat expansion as a mechanism of anticipation) in Friedreich ataxia.

3. At the very least, we cannot leave out X-linked in combination with genetic anticipation (I would think Fragile X is the most prevalent condition involving genetic anticipation).

4. I think the HPO sees Genetic Anticipation and other Mode of Inheritance terms as things that can co-occur (like @cbizon's proposal (1)).

5. Interestingly, the [HPOweb entry for _FMR1_](http://compbio.charite.de/hpoweb/showterm?gene=2332) (the gene associated with Fragile X syndrome) lists "X-linked Inheritance" and "X-linked dominant inheritance" (the latter is a subclass of the former) but does not list "Genetic Anticipation". Furthermore, the [entry for Premature Ovarian Failure 1](http://compbio.charite.de/hpoweb/showterm?disease=OMIM:311360) (which is associated with _FMR1_ as well) lists "X-linked inheritance" but does not list "X-linked dominant inheritance", and doesn't have a "Sex-limited" term (since the only Sex-limited term in HPO is under AD...). Clearly HPO isn't capturing all of the possibilities. I note that there is a "Male-limited Autosomal Dominant" term under "Sex-limited Autosomal Dominant", but not a "Female-limited Autosomal Dominant" term, which hardly seems fair...

**Comment by rrfreimuth** [comment]
I was out all last week – sorry for getting behind – trying to catch up.

When I encounter situations like this, where a bucket of terms is tying me in knots because of the partial/conditional overlap of assorted qualifiers, I usually find that it is caused by trying to precoordinated orthogonal concepts into a single term.  I’m not suggesting we take on the task of trying to clean up the terminology, but if we could define those orthogonal concepts we might be able to define more tightly scoped value sets for each, thereby avoiding the issue.

Or that could just be wishful thinking.  Happy to discuss if desired, or ignore if the group has already come to consensus and moved on.

Thanks,
Bob

**Comment by bpow** [comment]
Yes, we (and the HPO) are probably conflating concepts that are different.

Especially with regard to Genetic Anticipation. This was initially described as a phenotypic effect, but all of the cases that I can think of that demonstrably exist reflect a mechanism of repeat expansion (which is a mutational mechanism, not a mode of inheritance...).

**Comment by cbizon** [comment]
From my reading of the clinvar XSD, it appears to me that you could define more than one mode of inheritance.   MOI just goes into an attribute set, and you can put arbitrary numbers of attributes, I think.  Not sure if that's reflected in the submission process or not.
