### ISSUE TITLE
Terminology "Code" Creation and Management

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#91]
Observation and Opinion only (for what its worth).  
I do agree that we have some responsibility for defining terminology and value sets, particularly where there is none or where we've created a need in our data structures. 

However, it is a tricky business, which is why some groups take the tact of defining a "classical" or well-establish set of codes and then allow the community to extend it. Of course the more that you know that the list is static you can withdrawal the extensibility and make it required (or restricted).  

I think we can spend a good deal of time address all the nuances of the different terms and flavors of coded concepts but I would prefer to point to HPO or some other group to the extent something is available and simply list the top flavors and make it extensible.

Let the users use it for a period of time so they can suss out the terms that provide the right level of specificity and can be published in standardized ontologies down the road.

For example, take a look at the list of inhertiance mode values in ClinVar.  This will give you a sense of how folks use it.  And, I understand we want to try to "force" folks down a better path.  But how can we be sure our terminology expertise and application is "better" than others?

Providing a nudge in a direction with a limited value set of demonstrably acceptable terms that can be extended seems much more inviting and productive (to me) than mandating a fixed list, unless of course we are going to provide the support and documentation for our terminology services at the degree any public authority would (which does not seem realistic - long term).

**Comment by bpow** [comment]
At the risk of [developing another standard](https://xkcd.com/927/), sometimes there are problems using existing coded concepts for our use cases (the issues of mode of inheritance in HPO described in #88 illustrate this).

This being said, I think there is an analogy to @tnavatar's suggestion for two schema/contexts-- a more strict one for what we say that we would produce/use within ClinGen and one that is looser/more open to extension.

To frame that in the current discussion, I think we are already doing this by generating using `Codings`-- people are free to use different codings. I'm not sure that we can completely delegate to external code systems for core types for the internal use case, because we should try to clean things up when we see problems.

I'm not sure how much that moves the discussion further, but I'm not sure I really understand @larrybabb's concerns about the process we are currently undertaking with regards to Codings and ValueSets.

**Comment by cbizon** [comment]
I will be honest - I do not understand what @larrybabb  is proposing (though I think that I understand his concerns).

I can imagine cases where moving to codableconcept might be the right answer (Mode of Inheritance?)

**Comment by larrybabb** [comment]
Sorry for the wasted time on this topic.

It was a bit of a running thought with little or no focus or solution to speak of.

I think the concern of taking on the challenge of defining Codings and vocabularies as comprehensively as we can being "tricky" business is something we will see or not.  If so, we can deal with it at that time as a group with a collective and clear understanding.

I'm going to close this for now and try to be more constructive going forward.
