### ISSUE TITLE
Are ValueSets 018,019 "real"?

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#97]
Value Set 18 and 19 are disease and phenotype. Is there some reason to provide these value sets?  We are not going to enumerate them all.

**Comment by bpow** [comment]
This gets back to the discussion about ValueSets that may be "enumerable" vs. ValueSets that merely delegate to a specific system. Some of the latter may actually be enumerable, but we are not interested in doing so because an existing ontology already does so.

We don't really have a way to represent this in terms of validation of ValueSets yet, but we list the codings used in our examples as being members of these ValueSets for purposes of documentation.

I'm not sure that this answers your question (maybe @larrybabb would like to comment), but I think that this level of validation is outside of the scope of the initial release.

**Comment by cbizon** [comment]
Right, but I guess the question is do we need a valueset at all for these concepts?

**Comment by larrybabb** [comment]
If we don't want to deviate from the spirit of the HL7 terminology spec on valuesets, then we do need the value set, but we don't have to specify any values, we can simply state a coding system with a filter (or none if appropriate).  

You can see examples of this in FHIR [here](https://www.hl7.org/fhir/valueset-body-site.html) . 

In that example, the section titled "Content Logical Definition" is a bulleted list of explanations for the source of content and/or a list of explicit items (subset) from a given system.  Then the "Expansion" section attempts to show every possible value (or the first 1000 if possible).

We really only need to do the "Content Logical Definition" kind of thing. IMO

**Comment by larrybabb** [comment]
closing as a result of the SEPIO/ClinGen harmonization work.
