### ISSUE TITLE
id vs system in codings.

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#98]
The codings currently look like this:

 ```{
      "id": "CG-data-source:app",
      "type": "Coding",
      "code": "app",
      "system": "http://clinicalgenome.org/datamodel/data-source/",
      "display": "application"
    }
```

should id be `"http://clinicalgenome.org/datamodel/data-source/app"` ? 
or should system be `"CG-data-source"` ?

Where is `CG-data-source` defined?   Presumably in a context that is not listed?

Finally, what is the most stable thing here to code against for VCI translation?  System+code looks like the right answer to me.

**Comment by tnavatar** [comment]
I agree with you Chris, I think in this instance we're assuming that there's a context somewhere that says "CG-data-source": "http://clinicalgenome.org/datamodel/", so the ID for this is already system+code.

In a separate issue I'm going to argue for a flatter IRI structure for our terms, using numeric rather than textual identifiers.

**Comment by larrybabb** [comment]
I also concur, but would like to make a clarification in terms of the CG code systems and value sets.

The CG code systems must be defined such that the codes within them will be unique.  So, they end up looking much more like a 1-to-1 with the ValueSets, since we do not author a formal coding system that assigns unique codes (or ids) to each term we create (like SNOMED, LOINC, HPO, etc..)  

So our CG code systems would not equate to "http://clinicalgenome.org/datamodel/", but rather "http://clinicalgenome.org/datamodel/<cg-sub-system>/", where <cg-sub-system> can be any one of the dozen or so mini-codesystems that we manage using alpha code terms that are only guaranteed to be unique within the mini-codesystem namespace.

I'm only adding this indirectly related point so it is crystal clear. And because the above statement in @tnavatar 's comment is not 100% accurate...
"CG-data-source": "http://clinicalgenome.org/datamodel/"
really should be
"CG-data-source": "http://clinicalgenome.org/datamodel/data-source/"

which (BTW) happens to be a specific code system that we removed yesterday.  But the pattern still holds for all the others.

**Comment by tnavatar** [comment]
Thanks for the update on this Larry, I have a couple questions:

1) Regarding the mini-code systems: why can't we simply use the same (flat) IRI for terms we create, and provide the guarantee that all terms have unique identifiers (because we created them).
2) We aren't considering our own curated subsets of other people's code systems to be a part of these mini-ClinGen systems, are we? (for example, Chris's subset of inheritance terms defined in HPO)

**Comment by larrybabb** [comment]
1. We could use the same IRI for terms we create (across all value sets) if we took the time and care to make sure our codes are unique. We would most likely want to institute a sequence numbering approach and thus log and curate them.  Currently, we simply came up with little shorthand or abbreviated alpha terms for codes and we only really validate that they are unique within a give sub-code-system (which maps to a valueset).  This is the model that HL7 uses when they need to create codes to fill the many gaps created by all the resources they share in the healthcare domain.  
#2 None of the public codes that are pulled into our ValueSets (i.e. HPO, SO, etc..) would be part of our code systems (mini or not).  A code system has a single authorizing agency which manages and assures the availability, immutability, consistency, durability and uniqueness of the codes in that code system.  A single authorizing agency can have multiple code systems (i.e. NCBI, HL7).  It really all depends how an authorizing agency wants to slice and dice and publish sets of codes.

**Comment by tnavatar** [comment]
I see what you mean Larry, so https://www.hl7.org/fhir/codesystem-composition-status.html <https://www.hl7.org/fhir/codesystem-composition-status.html> is an example of what you’re talking about, right?

I’ve been using an ontology to hold some of the codes I’ve been creating to represent gene dosage (which I should share with this group at some point), Protege makes it easy to create auto-numbered IRIs and is a reasonably easy tool to use otherwise. That said, dealing with OWL ontologies programmatically is a (much) bigger pain than, say downloading our current spreadsheet in CSV form, and would represent a pretty big shift in our workflow.

**Comment by cbizon** [comment]
This issue is obsoleted by UserLabel and other things....
